### ISSUE TITLE
VS 2017

### ISSUE THREAD

**Issue by tommyready** [weggetor/BBQuery#1]
Do you have a solution that will open in VS 2017?  I get errors trying to open.

**Comment by weggetor** [comment]
Hi tommyready,

Thats because of the automatic packaging when building in release mode. To make it work you have to install two packages on your machine:

MSbuild Community Tasks: This is an open source project and contains multiple extensions for the MSBuild engine. Download from here: http://msbuildtasks.tigris.org/files/documents/3383/28296/MSBuild.Community.Tasks.msi

DnntcMsBuild: Includes build routines to create the DNN manifest. Tweaked by myself to add creation of language packages and other minor changes.
https://www.bitboxx.net/Portals/0/Blog/DNNWithAngular5/DNNtc.MSBuild.VSSetup.msi

**Comment by tommyready** [comment]
@weggetor Thanks.
Once I installed those I went into the file: \Installation\Project.targets and hard coded the path then after that the project opened.
